spring:
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  profiles:
    active: dev

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 1 hour duration by default: 1 hour * 60 minutes * 60 seconds * 1000 milliseconds

UserController:
  signIn: Authenticates user and returns its JWT token
  signUp: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  uploadProfilePicture: Uploads new profile picture for the currently logged user
  getProfilePicture: Returns profile picture for the specific user

FamilyTreeController:
  getTrees: Returns all public trees for the specific user and all private if the request is send by their owner
  getTree: Returns public Family Tree with specific id
  createNewTree: Creates new Family Tree without members
  updateTree: Updates your already created Family Tree
  deleteTree: Deletes your Family Tree
  findTrees: Returns all Family Trees matching an expression

FamilyMemberController:
  getMembers: Retrurns all Members of the specific Family Tree
  addMember: Add new Member to existing Family Tree
  updateMember: Updates already existing Member in Family Tree
  deleteMember: Deletes already existing Member from Family Tree

PublicController:
  ping: Checks whether the server is working
